### ISSUE TITLE
Add a Cloudflare snippet to the FAQ

### ISSUE THREAD

**Issue by thebrandonallen** [thebrandonallen/wp-fail2ban-redux#15]
https://stackoverflow.com/a/14985633
https://stackoverflow.com/a/38298029
https://core.trac.wordpress.org/ticket/9235#comment:39

**Comment by thebrandonallen** [comment]
Fixed in c45df7e0d04ba525cccc085a0c01c2ec1ae29599

**Comment by dvershinin** [comment]
Fail2ban by default blocks IP address in server's firewall. If the connections are originated from Cloudflare IPs, blocking "restored IPs" will not yield any results, because those restored IP addresses never really access the server.

These links should be supplemented with information on how to teach Fail2ban to block IPs on the Cloudflare side, only then it will all be working as intended.
